services:
  yogurt:
    build: .
    image: yogurt:latest
    container_name: yogurt
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
    environment:
      - YOGURT_DATA_DIR=/app/data
